### ISSUE TITLE
Third Person breaks

### ISSUE THREAD

**Issue by frqnny** [56738/SmoothCoasters#3]
I love the mod! But it breaks third person on 1.17 fabric using the latest (just downloaded it today)

**Comment by frqnny** [comment]
For more information, this only seems to happen in this Walt Disney World monorail on a server. You can test this at iears.us (1.17.x server) has custom resource pack and thus model TC coaster. riding a monorail will make it so that the third person breaks for some reason.

**Comment by 56738** [comment]
Sorry for the late response, I've been taking a break from this for a while.

The latest [dev build](https://ci.mg-dev.eu/job/TrainCarts/) of TrainCarts should fix this - it uses a [new rotation mode](https://github.com/bergerhealer/TrainCarts/pull/435) which doesn't have this problem.

I've also released an update for the mod which disables camera rotation in third person in the old mode.
